Contribute case studies to the guide
BitcoinDesign/Guide pull request #1022
Opened 2023-07-06 08:02 UTC by mouxdesign

This initial commit is a draft version of the page guiding people on how to commit a case study to the guide.

2023-07-17 09:24 UTC, GBKS requested changes
Great to see this page take shape. I left a lot of small comments, hope it's all useful.

Make sure to preview the site on your local dev environment before you commit. When the site is getting built for your preview, it also looks for new images and compresses them. The images in this PR are not compressed and pretty huge. Since they are not primarily flat shapes and lines, JPEG will also be more appropriate for a better compression.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +title: Case Studies
```suggestion
title: Case studies
```
We use sentence case everywhere.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +description: How to contribute case studies to the guide
```suggestion
description: How to contribute case studies to the guide.
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +image: https://bitcoin.design/assets/images/guide/contribute/contribute-preview.jpg
You need a custom preview image for this page that's 1200x630px.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +   image = "assets/images/guide/contribute/case-studies/CasestudiesHeader.png"
[Guidelines for file names](https://bitcoin.design/guide/contribute/illustration-guidelines/#file-names).

JPEG should be smaller here than PNG ([guidelines](https://bitcoin.design/guide/contribute/illustration-guidelines/#jpg-png-or-gif)).

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +   retina = "assets/images/guide/contribute/case-studies/CaseStudiesHeader2X.png"
Use `@2x` to indicate retina images.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +   alt-text = "Image of people reading books"
The screen reader already knows this is an image, no need to repeat (see [alt text writing tips](https://webaim.org/techniques/alttext/)).

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +   height = 800
```suggestion
   height = 268
```
Your image file is not 800px tall, but 268px.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +# Case Study Guidelines
```suggestion
# Case study guidelines
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +There are various types of case studies. Some document proven solutions in the ecosystem, others are short, to the point stories of how a designer or team solved a particular challenge. This document
```suggestion
There are various types of case studies. Some document proven solutions in the ecosystem, others are short, to the point stories of how a designer or team solved a particular challenge. This document is intended to help you write one of the latter. Ideally, a case study that is digestible for a wider audience, would be in the range of 1-4 pages in length.
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +* How did this problem come to the source? What was the background?
```suggestion
* How did this problem come to the source? What was the background?
```
To the `source`? Do you mean `surface`?

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +   modalHeightMobile = 400
```suggestion
   modalHeightMobile = 271
```
Your mobile image is 271px tall.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +   alt-text = "User personas example"
The alt text can be more descriptive.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +Example of user persona Payjoin case study
Accidental repeat of this sentence? It's also above the image.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +Example of user persona Blixt wallet case study
```suggestion
Here's an example of a user persona from the [Blixt wallet case study]({{ '/guide/case-studies/blixt-wallet/' | relative_url }}).
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +* Images of userflows or snapshots of research done. Anything visual can go here that helps to tell a bit of a story. These can be messy.
```suggestion
* Images of user flows or snapshots of research done. Anything visual can go here that helps to tell a bit of a story. These can be messy.
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +* An image showing the main insights, if you have one.
```suggestion
* An image showing the main insights, if you have them.
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +* Bullet points highlighting the main insights.
Both paragraphs above already talk about main insights. Feels a bit repetitive. Can we mix this up a little? I think it's fine to leave the points about insights, but each section can take a different angle. Visuals can be about annotated screenshots or other material. The Insights paragraph itself can describe those insights in detail. And content ideas can build on those insights to generate improvements.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +### Content ideas
Don't think you need this "Content ideas" title again. We just saw another one of those just a little further up. Maybe just remove it?

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +This is the last section of the case study where it’s nice to share links to all the parts; or rather the puzzle pieces. Here you can add in simple titles such as a Figma file or links to research co
```suggestion
This is the last section of the case study where it’s nice to share links to all the parts; or rather the puzzle pieces. Here you can add in simple titles such as a design file or links to research conducted. Add all the artefacts that were used in the entire design process to give the reader the option to dive in and keep learning from your experience.
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +The below 2 case studies were put together roughly using the above guidelines.
```suggestion
The below two case studies were put together using roughly the above guidelines.
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +   previousUrl = "/guide/review/"
Previous page is not right, should be the [Media page](https://bitcoin.design/guide/contribute/formatting/media/).

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +   nextUrl = "/guide/daily-spending-wallet/"
Next page is not right. Should be the [Glossary](https://bitcoin.design/guide/glossary/).

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +* [Blixt](/guide/case-studies/blixt-wallet/)
```suggestion
* [Blixt]({{ '/guide/case-studies/blixt-wallet/' | relative_url }})
```
We need to use this more complicated format for internal links.

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/case-studies.md
> +* [The Payjoin experience](/guide/case-studies/payjoin/)
```suggestion
* [The Payjoin experience]({{ '/guide/case-studies/payjoin/' | relative_url }})
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/contribute.md
> +### [Case Studies]({{ '/guide/contribute/case-studies/' | relative_url }})
```suggestion
### [Case studies]({{ '/guide/contribute/case-studies/' | relative_url }})
```

2023-07-17 09:24 UTC, GBKS commented on guide/contribute/contribute.md
> +---
```suggestion

---
```
Make sure to preview this text. It's rendered really big in the site. Not sure exactly why, but it probably just needs an extra line break between the text and the dashes.

2023-07-18 00:21 UTC, mouxdesign commented on guide/contribute/case-studies.md
> +* How did this problem come to the source? What was the background?
Correct, changed

2023-07-18 00:21 UTC, mouxdesign commented on guide/contribute/case-studies.md
> +   alt-text = "User personas example"
Added.

2023-07-18 00:22 UTC, mouxdesign commented
Thanks a lot for going through all the code Christoph. I continued to work on it and accepted the copy edits.

Also the copy/url ones that I marked as resolved I fixed those in the latest commit in a batch. 

Still to work on Images.

2023-07-21 05:10 UTC, rabbitholiness commented
Just went through the page. Looks good to me. 

The only thought I had was that it might be nice to have a sample "table of contents" or "structure" in the initial section, which let's the reader quickly get an idea of what a case study should contain, before they dive into the details of the page. Something like:

Example structure
1. How it started (Introduction)
2. User base
3. Methodology
4. Insights
5. Conclusion
6. Resources
7. Acknowledgement

2023-07-21 05:54 UTC, GBKS commented
If you want to add a table of contents, you just need to add a bit of code, as follows:

<img width="354" alt="image" src="https://github.com/BitcoinDesign/Guide/assets/695901/9787248b-3125-475f-b7be-a8c17c86a4ce">

`{:.no_toc}` tells it to not include the page title in the table of contents.

And the following snippet automatically creates a table of contents from the headers used on the page.

```
<div class="glossary-toc" markdown="1">
* Table of contents
{:toc}
</div>
```

2023-08-08 19:18 UTC, GBKS requested changes
Lots of issues with images, please take another look.

2023-08-08 19:18 UTC, GBKS commented on _compress_images_cache.yml
> +<<<<<<< Updated upstream
Your preview site is not building because there are unresolved merge issues in this image cache file. Remove lines 2211, 2212, and 2231.

2023-08-08 19:18 UTC, GBKS commented on guide/contribute/case-studies.md
> +image: https://bitcoin.design/assets/images/guide/contribute/contribute-preview.jpg
Still need this image.

2023-08-08 19:18 UTC, GBKS commented on assets/images/guide/contribute/case-studies/casestudy-contribute-custom-image.jpg
This image is waaaaaay huge at 32768x12899px and 49.1 MB.

2023-08-08 19:18 UTC, GBKS commented on assets/images/guide/contribute/case-studies/casestudies-header-mobile@2X.jpg
Please lowercase the "X" in all the file names as well.

2023-08-08 19:18 UTC, GBKS commented on guide/contribute/case-studies.md
> +   customImage = "assets/images/guide/contribute/casestudy-contribute-custom-image.jpg
Not sure where this `customImage` attribute comes from, but this does not exist in `picture.html`. You can remove it.

2023-08-08 19:18 UTC, GBKS commented on guide/contribute/case-studies.md
> +   image = "assets/images/guide/contribute/casestudies-header.jpg"
All the file paths are incorrect here. Please double check.

2023-08-08 19:18 UTC, GBKS commented on guide/contribute/case-studies.md
> +   height = 268
```suggestion
   height = 264
```

2023-08-08 19:18 UTC, GBKS commented on guide/contribute/case-studies.md
> +   image = "assets/images/guide/contribute/case-studies/user-persona-example-blixt.jpg"
Image is not rendering due to inconsistencies in the file names.

2023-08-08 19:18 UTC, GBKS commented on assets/images/guide/contribute/case-studies/user-persona-example-blixt.jpg
I assume this image should be 1600x1080 (it is double that now).

2023-08-11 18:52 UTC, GBKS approved these changes
ACK. Let's get this merged. I think there could be some minor copy improvements, but those can be added in iterations as needed.

2023-08-11 18:52 UTC, merged