Inheritance wallet - Part 2 - Backup
BitcoinDesign/Guide pull request #1087
Opened 2024-05-02 17:38 UTC by rabbitholiness

This PR builds on [Part 1 of the Family Inheritance Wallet](https://github.com/BitcoinDesign/Guide/pull/1081) reference design. 

This page discusses how the backup process works and how the Joneses store and distribute different components of the backup material. 

👁️ [Check the preview here](https://deploy-preview-1087--bitcoin-design-site.netlify.app/guide/inheritance-wallet/backup/) 👁️

2024-05-13 08:52 UTC, mouxdesign reviewed
Read through the copy, quite an intricate topic here but the diagrams are a great thing which accompany the copy.
Added in some ideas about the images mostly and how they compliment the copy itself.

2024-05-13 08:52 UTC, mouxdesign commented on assets/images/guide/inheritance-wallet/wallet-backup/multikey-backup-components.png
In the diagram the word wallet descriptor is used, however in the copy wallet configuration is used in the opening paragraph and the copy below the image. Might be good to choose one term and use to it both with image and copy.

2024-05-13 08:52 UTC, mouxdesign commented on assets/images/guide/inheritance-wallet/wallet-backup/backup-kit-contents.png
It might make more sense here to create an example of one wallet, for understanding the context of the image more. one wallet name then showing many different file types. The image used does make sense as it seems you are trying to convey that different wallets can use different file types but the relatedness of those file types is confusing visually. If that relatedness could be grouped or shown, might make more sense.

2024-05-13 08:52 UTC, mouxdesign commented on assets/images/guide/inheritance-wallet/wallet-backup/multikey-backup-components.png
Wallet descriptor copy in image: 
"A small piece of text", further below in the copy it seems that the small piece of text is the backup kit. Might be worth changing the copy in the image to keep it consistent. 

If I understand correctly the backup kit is exportable as a ZIP file.

2024-05-13 08:52 UTC, mouxdesign commented on guide/inheritance-wallet/landing-page.md
> +{% include image.html
This image does not seem to show up on my end. 
![Screenshot 2024-05-13 101624](https://github.com/BitcoinDesign/Guide/assets/90313394/b94a2188-7829-4979-8751-8f655181891a)

2024-05-13 08:52 UTC, mouxdesign commented on guide/inheritance-wallet/backup.md
> +As we have covered in the time-based recovery [reference design](https://bitcoin.design/guide/savings-wallet/time-based-recovery/#wallet-backup) there are two parts to backing up a multi-key wallet:
```suggestion
As we have covered in the time-based recovery [reference design](https://bitcoin.design/guide/savings-wallet/time-based-recovery/#wallet-backup) there are two parts to backing up a multi-key wallet: the private keys as well as the wallet configuration.
```
```suggestion
As we have covered in the time-based recovery [reference design](https://bitcoin.design/guide/savings-wallet/time-based-recovery/#wallet-backup) there are two parts to backing up a multi-key wallet: 
1. Private keys 
2. Wallet configuration
```

2024-05-13 08:52 UTC, mouxdesign commented on guide/inheritance-wallet/backup.md
> +This means that, in our use case, the Joneses need to safely backup and store six private keys as well as the wallet configuration.
Idea to remind the reader of the use case here, could mention it as one sentence or link back to it.

2024-05-13 08:52 UTC, mouxdesign commented on assets/images/guide/inheritance-wallet/wallet-backup/multikey-backup-components.png
Suggestion to image copy:
Heading: Wallet configuration.
Body copy: A pdf file as well as wallet backup files in various contexts that a wallet would need to recover a multi-key wallet.

2024-05-13 08:52 UTC, mouxdesign commented on guide/inheritance-wallet/backup.md
> +The illustration above reveals that Christina and David can access in two different ways.
```suggestion
The illustration above reveals that Christina and David can access the multi-key wallet in two different ways.
```

2024-05-13 21:27 UTC, yashrajd requested changes
I'd been eagerly waiting for the backup page PR, so happy to see how it's turning out. The sections on backup distribution & assembly are especially great IMO.

Hope my inputs are helpful, if some of them look convoluted to do reach out.

2024-05-14 06:30 UTC, rabbitholiness commented on guide/inheritance-wallet/backup.md
> +Alice and Bob then encrypt the ZIP file with a strong password and both of them stores a copy of it in their personal password manager account, case they need to recover the wallet themselves.
Yeah, I thought of that at as well, but then users would have to place more trust in the application. Don't know whether that would be a problem, though.

2024-05-29 13:54 UTC, rabbitholiness commented on assets/images/guide/inheritance-wallet/wallet-backup/multikey-backup-components.png
Updated and rephrased. Hope it makes more sense now.

2024-05-29 13:54 UTC, rabbitholiness commented on assets/images/guide/inheritance-wallet/wallet-backup/backup-kit-contents.png
Updated and made a more concrete example. Hope it's clearer now.

2024-06-24 11:12 UTC, GBKS requested changes
Looking good. Just had some minor comments. Make sure that images are as legible as possible on mobile by providing vertical layouts as needed.

2024-06-24 11:12 UTC, GBKS commented on guide/inheritance-wallet/backup.md
> +{% include picture.html
The information definitely looks nicer as an image, but is also less accessible and super hard to read on mobile. You could. You could pull the text into the HTML or add a separate mobile image with a vertical layout.

2024-06-24 11:12 UTC, GBKS commented on guide/inheritance-wallet/backup.md
> +The inheritance wallet described in this reference design is a multi-key wallet with time-based recovery. When backing up such a wallet, users must back up not only their own private keys but also th
Make sure to use relative links instead of absolute ones. Several instances of that on this page.

2024-06-24 11:12 UTC, GBKS commented on guide/inheritance-wallet/backup.md
> +{% include picture.html
Make sure to add a mobile version with a vertical layout for easier reading.

2024-06-24 11:12 UTC, GBKS commented on guide/inheritance-wallet/backup.md
> +Please note that this is one of many possible ways to approach wallet backups and should not be understood as the only correct way to do it.
You could use [tip formatting](https://bitcoin.design/guide/contribute/formatting/#tips--recommendations) here.

2024-06-24 11:12 UTC, GBKS commented on guide/inheritance-wallet/backup.md
> +We would also like to reiterate the point made in the "Use case & scope" page: the complexity of the backup scheme increases with the complexity of the wallet configuration. Therefore, user education
> "Use case & scope"

Best to make that a link.

2024-07-08 10:51 UTC, closed without merging

2024-07-08 10:52 UTC, rabbitholiness commented
I'll open a new PR as I had technical issues with this branch.