Inheritance wallet - Part 3 - Cosigner onboarding & key replacement
BitcoinDesign/Guide pull request #1091
Opened 2024-05-14 09:56 UTC by rabbitholiness

This PR builds on the previous inheritance wallet PRs:
[Part 1: Use case & wallet creation](https://github.com/BitcoinDesign/Guide/pull/1081)
[Part 2: Wallet backup](https://github.com/BitcoinDesign/Guide/pull/1087)

It adds a page about how Alice is set up as a cosigner for the family savings wallet. It also adds a page about key replacement and wallet archival.

2024-05-14 10:07 UTC, rabbitholiness commented
Opened this PR in draft mode so far, so that people can look at it. There's quite a few things to tweak:
- Image captions & alt-texts
- Consistency checks
- Navigation & reference links
- Potentially additional clickable prototypes

2024-05-16 14:22 UTC, rabbitholiness commented
Opening this up for initial feedback, even if there are two things left to do:
- Write alt-texts for the 66 images in this PR 😊
- Create a visual for the ["how it works" section](https://deploy-preview-1091--bitcoin-design-site.netlify.app/guide/inheritance-wallet/making-changes/#how-it-works) of the "Making changes" page, for better clarity.

2024-06-21 08:43 UTC, rabbitholiness commented on guide/inheritance-wallet/onboarding-cosigners.md
> +2. Enable her Bitbox to sign transactions.
I see your point. However, I would probably keep the device names. I know they're brands, but I think it's easier for the reader to follow along, if they are specific examples. In addition, these brands have been around for a long time, so I wouldn't be too worried about that.

2024-06-24 09:50 UTC, GBKS commented on guide/inheritance-wallet/onboarding-cosigners.md
> +2. Enable her Bitbox to sign transactions.
How about we make up our brands - BitGuard, CoinSafe, and BlockVault? I've done this before with mock-ups and it usually works well.

2024-06-24 09:52 UTC, GBKS commented on guide/inheritance-wallet/onboarding-cosigners.md
> +2. Enable her Bitbox to sign transactions.
Example:

![image](https://github.com/BitcoinDesign/Guide/assets/695901/fee6e4cf-0ed2-48f8-ab2a-d4f8530a5d06)

2024-06-24 12:02 UTC, GBKS requested changes
Looking good. Just some minor feedback.

2024-06-24 12:02 UTC, GBKS commented on guide/inheritance-wallet/making-changes.md
> +On the app home screen, Alice now sees a reminder that a transaction is ready to be signed. On the detail screen, she also sees that Bob has already provided a signature. Alice hits "sign" and goes t
> now sees a reminder that a transaction is ready to be signed

How does the app know about the transaction? Is there a server handling communication? If not, then Bob would have to share the PSBT.

2024-06-24 12:02 UTC, GBKS commented on guide/inheritance-wallet/making-changes.md
> +### Archiving the old wallet
Could cross-link to the [archival paragraph](https://deploy-preview-1091--bitcoin-design-site.netlify.app/guide/multiple-wallets/#archival) in the multi-wallet page somewhere.

2024-07-08 10:56 UTC, closed without merging

2024-07-08 10:57 UTC, rabbitholiness commented
I will open a new PR, as I had technical issues with the existing branch.