Inheritance wallet - Part 4 - Recovery
BitcoinDesign/Guide pull request #1096
Opened 2024-06-21 08:49 UTC by rabbitholiness

This is the last part of the inheritance wallet reference design. This PR adds a page about wallet recovery. It describes how Christina and David use their inheritance keys to recover their parents' wallet and access their inheritance. 

👀 Check the preview [here](https://deploy-preview-1096--bitcoin-design-site.netlify.app/guide/inheritance-wallet/wallet-recovery/) 👀

2024-06-24 12:19 UTC, GBKS requested changes
Looking good. Some minor feedback, and a request for adding more info to the wrap-up.

I am also wondering it the page title is right. Recovery sounds like something got lost. But what's being described is part of the planned inheritance process. Is there maybe a good context-specific term? Succession? What do you think?

2024-06-24 12:19 UTC, GBKS commented on guide/inheritance-wallet/recovery.md
> +This page covers a multi-key wallet that uses timelocks to provide additional recovery options.
Update to match this page.

2024-06-24 12:19 UTC, GBKS commented on guide/inheritance-wallet/recovery.md
> +One day, a couple of years later, Christina and David get sad news that their parents, Alice and Bob, were involved in a deadly car accident. While dealing with the inheritance proceedings, Christina
> One day, a couple of years later

Later? I assume it's referencing the wallet setup. Maybe change it to `a couple of years after the family set up their inheritance wallet`?

2024-06-24 12:19 UTC, GBKS commented on guide/inheritance-wallet/recovery.md
> +After the timelock for the inheritance key set expires, Chrstina and David get together over dinner. They want to send half of the funds to Christina’s personal wallet and the other half to David’s w
```suggestion
After the timelock for the inheritance key set expires, Christina and David get together over dinner. They want to send half of the funds to Christina’s personal wallet and the other half to David’s wallet.
```

2024-06-24 12:19 UTC, GBKS commented on guide/inheritance-wallet/recovery.md
> +The transaction has been created and is ready to be signed. Christina goes ahead and sings it with her hardware signing device.
Could this be a batch transaction? Would save fees and reduce the number of signing rounds.

2024-06-24 12:19 UTC, GBKS commented on guide/inheritance-wallet/recovery.md
> +
The funds are now distributed to the heirs, but the social & legal process is not finished. The lawyer may need to be informed, maybe they need to take screenshots of the fund distribution (like a receipt) for future reference. Maybe they also want to delete the wallet data, swipe the signing devices, or other stuff. Just made this up quickly, but that clean-up might be a good way to wrap up.

2024-07-08 10:58 UTC, closed without merging

2024-07-08 10:58 UTC, rabbitholiness commented
I will open a new PR, as a I had technical issues with the branch.