Contribute page review structure & checklist
BitcoinDesign/Guide pull request #1117
Opened 2024-09-24 09:31 UTC by GBKS

I complained a bit yesterday about some common issues I find across PR reviews, and Yashraj recommended creating a checklist. So here it is.

This PR expands on the process for requesting reviews and proposes a 3-step structure. It also adds a common issues checklist for general and smaller things to look out for before requesting reviews.

I am keeping this as a draft as I'd like to share it for now, but also do another iteration specifically looking out for cross-linking and referencing across other pages in the contribute section. Also curious to hear if others have items they'd like to put on the checklist.

2024-09-28 00:21 UTC, yashrajd requested changes
Did a first pass review, and overall it looks pretty good. Really appreciate how you've incorporated much of what I expressed during the silent payments PR review process. I've dropped a few suggestions and comments.

- One recommendation that I have may be added somewhere if it makes sense: keep Structural (or even Refinement stages) off the PR/github especially for bigger items, and open the PR only when you're half way or further. 

During the initial stages, the content is likely to change/move substantially and line-level feedback might not be needed or provided. It also keeps the content more accessible to folks who don't prefer Github.

2024-09-28 00:21 UTC, yashrajd commented on guide/contribute/propose-a-change.md
> +Your proposed changes need to undergo a [review process]({{ '/guide/contribute/review/' | relative_url }}). It often consists of several rounds of several rounds of feedback, for example:
```suggestion
Your proposed changes need to undergo a [review process]({{ '/guide/contribute/review/' | relative_url }}). It often consists of  several rounds of feedback, for example:
```

2024-09-28 00:21 UTC, yashrajd commented on guide/contribute/propose-a-change.md
> +The community may not automatically see when you post a new pull request. Make sure to ask in the [#bitcoin-design-guide](https://discord.gg/7Z6z8cetwu) Discord channel, and reach out to reviewers wh
```suggestion
The community may not automatically see when you post a new pull request. Make sure to ask in the [#bitcoin-design-guide](https://discord.gg/7Z6z8cetwu) Discord channel, and reach out to reviewers whose specific feedback you would appreciate. You can also organize a reading session for your content, so far they have always been extremely helpful.
```

2024-09-28 00:21 UTC, yashrajd commented on guide/contribute/propose-a-change.md
> +1. **Structural:** Reviewers look at how the new content fits in with the existing content in the guide. They check if it's generally appropriate, complete and accurate, and if it reads well. It give
I think the content reading well belongs in the Refinement stage, or even Polish stage.

```suggestion
1. **Structural:** Reviewers look at how the new content fits in with the existing content in the guide. They check if it's generally appropriate, complete and accurate. It gives you confidence that you are working in the right direction.
```

2024-09-28 00:21 UTC, yashrajd commented on guide/contribute/propose-a-change.md
> +This is generalized and your process may look different. In your pull request, and when requesting reviews, make sure to clearly communicate the type of feedback you are looking for. This makes the r
```suggestion
This is a generalization and your process may look different. In your pull request, and when requesting reviews, make sure to clearly communicate the type of feedback you are looking for. This makes the review task easier and more focused, and leads to more helpful responses.
```

2024-09-28 00:29 UTC, yashrajd commented
**Sorry the following is feedback for the page in general and not limited to this PR**

I also wonder how much GitHub must be a part of 'proposing a change'. Much of the content here is likely to be applicable whether or not somebody opens a PR. It can also be a steep learning curve for non-technical people, and I'd figure we want to make this process as accessible as possible.

If the above makes sense, perhaps the checklist might appear somewhere else maybe higher up on the page but possibly more changes needed then...

2024-10-16 18:51 UTC, danielnordh submitted a review, later dismissed
LGTM

2024-10-21 13:09 UTC, GBKS commented on guide/contribute/propose-a-change.md
> +- A simpler writing style allows your content to be more accessible to more readers (especially ones for whom english is not their native language)
I see think that's fine. This checklist is a bit of a summary of things that are explained in more detail elsewhere, so some repetition is OK.

2024-10-21 13:09 UTC, GBKS commented on guide/contribute/propose-a-change.md
> +- Delete unused images from your PR
Yep, but it has to be done.

2024-10-21 13:11 UTC, GBKS commented on guide/contribute/propose-a-change.md
> +- Compress your images via tool like [ImageOptim](http://imageoptim.com) (can save ~70% of bandwidth)
If you use a tool like ImageOptim, it will not compress images twice. Just drag all your pics in, let it do its thing, and you're good to go.

2024-11-11 12:31 UTC, mouxdesign approved these changes
Made some minor suggestions other than that LGTG

2024-11-11 12:31 UTC, mouxdesign commented on guide/contribute/propose-a-change.md
> +Your proposed changes need to undergo a [review process]({{ '/guide/contribute/review/' | relative_url }}). It often consists of  several rounds of feedback, for example:
```suggestion
Your proposed changes need to undergo a [review process]({{ '/guide/contribute/review/' | relative_url }}). It often consists of  several rounds of feedback, these rounds usually include the following:
```

2024-11-11 12:31 UTC, mouxdesign commented on guide/contribute/propose-a-change.md
> +The community may not automatically see when you post a new pull request. Make sure to ask in the [#bitcoin-design-guide](https://discord.gg/7Z6z8cetwu) Discord channel, and reach out to reviewers wh
```suggestion
The community may not automatically see when you post a new pull request. Make sure to ask in the [#bitcoin-design-guide](https://discord.gg/7Z6z8cetwu) Discord channel, and reach out to reviewers whose specific feedback you would appreciate. You can also organize a [reading session](https://www.youtube.com/watch?v=hjgpNVRe4uY) for your content, so far they have always been extremely helpful.
```

2024-11-11 12:31 UTC, mouxdesign commented on guide/contribute/propose-a-change.md
> +The community may not automatically see when you post a new pull request. Make sure to ask in the [#bitcoin-design-guide](https://discord.gg/7Z6z8cetwu) Discord channel, and reach out to reviewers wh
An idea to add in a link to a reading session review call.

2024-11-11 15:06 UTC, mouxdesign approved these changes

2024-11-11 15:11 UTC, merged