PKM - Rename Recovery phrase page
BitcoinDesign/Guide pull request #319
Opened 2021-05-14 12:29 UTC by danielnordh

Changing from 'Manual backup / Recovery phrase' on page, and 'Manual backup' in navigation to 
'Recovery phrase' on both.

Text updates in the first sentence on the page still makes it clear it requires manual backup.
All links and references have been updated.

As discussed in #313

2021-05-14 12:53 UTC, pavlenex commented
I have to dive deep into the reasoning for these, but to me it does not seem like a beneficial change. I think the terminology currently used is easily understandable even without reading what it does. Also it plays well together with the onboarding section so the two sections really explain the subject well. 

Doing a change like this would require a major refactoring on onboarding as well, and I just don't consider it wortwhile.

2021-05-14 13:20 UTC, danielnordh commented
This was in light of suggestions from @Bosch-0 in #313 

I don't see the change as that big, certainly not requiring refactoring of the Onboarding chapter but I'll let other people give their views. 🤷‍♂️

2021-05-14 13:45 UTC, pavlenex approved these changes

2021-05-14 13:47 UTC, pavlenex commented
Ok, didn't look at the diffs, was under the impression the manual vs automatic is being changed, but in fact, you're just addressing the manual.

I still don't think it's a good change in terms of people understanding what recovery is, but if there was a discussion around it and consensus to go for it, then I'll bow and say ok.

2021-05-14 13:49 UTC, danielnordh commented
Thanks @pavlenex 

Let's wait to merge this for a bit and see if other people have comments here.

2021-05-14 13:51 UTC, pavlenex commented
@danielnordh It seems that onboarding is based on this https://deploy-preview-302--sad-borg-390916.netlify.app/guide/onboarding/backing-up-a-recovery-phrase/

maybe @ConorOkus can tell us if this PR will have an effect on his structure. A minor change may have a big effect on broken links and other chapters so I always try to be careful when we do changes like this, if not critical I wouldn't do it. But as I said if there was a consensus and it doesn't impact the onboarding work in #302 then let's proceed with it.

2021-05-17 03:54 UTC, Bosch-0 commented
This page it only talks about recovery phrase's. If it covered other manual backup methods I agree it would make more sense to keep it at manual backup. Recovery phrase is much more in line with what this page is actually about.

2021-05-17 04:25 UTC, Bosch-0 approved these changes

2021-05-17 07:31 UTC, GBKS commented
TBH, I like "Automatic cloud backup" and "Manual backup" because those terms describe the user experience well. Technically, "Automatic cloud backup" could also back up a recovery phrase, and in a "Manual backup", the user could also store their recovery phrase in the cloud (it's up to them), and an external signing device could also require manual backup of a recovery phrase. But getting into those technicals gets just really messy and confusing, so I'd just keep the original - it's done automatically for the user via cloud, or they manually have to figure it out. Not going to fight for any direction though, so please go ahead and decide what you think is the right way to go forward, considering how we reference this in the rest of the guide.

2021-05-17 07:35 UTC, pavlenex commented
>  it's done automatically for the user via cloud, or they manually have to figure it out

I'm on the same page.

2021-05-17 13:10 UTC, ConorOkus commented
> TBH, I like "Automatic cloud backup" and "Manual backup" because those terms describe the user experience well. Technically, "Automatic cloud backup" could also back up a recovery phrase, and in a "Manual backup", the user could also store their recovery phrase in the cloud (it's up to them), and an external signing device could also require manual backup of a recovery phrase. But getting into those technicals gets just really messy and confusing, so I'd just keep the original - it's done automatically for the user via cloud, or they manually have to figure it out. Not going to fight for any direction though, so please go ahead and decide what you think is the right way to go forward, considering how we reference this in the rest of the guide.

This is my thinking also...

2021-05-18 08:58 UTC, Bosch-0 commented
+1 this change

> TBH, I like "Automatic cloud backup" and "Manual backup" because those terms describe the user experience well.

This is assuming all cloud backups are / should be automatic, which isn't the case. 100% automatic isn't ideal. They should require the user to still click an 'I understand'  or 'skip cloud backup' button - so not fully automatic. Or have the user backup into the cloud once inside the app through a security center type setup similar to Muun. The latter is my preferred method. It simplifies on-boarding (users can enter the app straight away) and gives a great balance of usability and sovereignty. 

Having it completely automatic to me isn't doing the best job at setting users to being fully self-sovereign bitcoin users down the line - which is how bitcoin products should be designed. 

Having recovery phrase over manual backup is more explicit as that is all that page covers. Manual backup seems more ambiguous. As stated previously,  just having manual backup is really open ended as to what the content of this page covers. I think it's better to be very specific with how we name / write content as to make it as simple as possible to parse for readers. 

This is the thought process of someone reading to me:

1. Reader reads 'Private key management' heading - Okay this chapter is about managing private keys, got it.
2. Reader reads 'Manual backup' heading - Okay, what kind of manual backups does this section cover? Does this cover manually backing up my seed? Does this go into to distributing my backup manually? Why is their a Bitcoin backups page also, what does that cover if this covers manual backups?
3. User enters 'Manual backup' page - Okay, this page is just about backing up your recovery phrase, got it.

We should aim to not have readers questioning as to what each section covers of which the current 'Manual backup' heading does - the whole _don't make me think_ UX dogma. If the page just said recovery phrase (as that is all the page covers) it would be much easier to parse.

2021-05-18 08:58 UTC, Bosch-0 approved these changes

2021-05-18 09:06 UTC, danielnordh commented
I don't want to merge this PR as it stands in light of comments above.
I'll have another look, potentially 'Manual backup of recovery phrase', covering all bases.

2021-05-18 10:02 UTC, GBKS commented
There's only so much meaning you can pack into 2 word labels. I'd not overanalyze this and just pick titles that are generally intuitive and then ensure the page content is clear on the details.

2021-05-18 10:38 UTC, Bosch-0 commented
The only meaning that needs to be conveyed is that this page is about recovery phrases (as that is all that is covered). Recovery phrase > manual backups. It is not about manual backups which is a much wider reaching topic.

2021-05-18 13:49 UTC, GBKS commented
Something else to keep in mind is that the onboarding section will also have "Automatic cloud backup" and "Manual backup" pages ([preview](https://deploy-preview-302--sad-borg-390916.netlify.app/guide/onboarding/backing-up-a-recovery-phrase/), [PR](https://github.com/BitcoinDesign/Guide/pull/302)). We should be consistent.

2021-05-18 13:54 UTC, GBKS requested changes
We need to sort out how this plays with the "Manual backup" page that Conor is working on in the Onboarding section.

2021-05-19 00:48 UTC, Bosch-0 commented
If those pages cover similar content as PKM pages they should also be renamed.

2021-05-21 09:56 UTC, danielnordh commented on guide/private-key-management/cloud-backup.md
> +Next, let's look at [Recovery phrase]({{ '/guide/private-key-management/recovery-phrase/' | relative_url }}).
```suggestion
Next, let's look at [manual backup of recovery phrase]({{ '/guide/private-key-management/manual-backup/' | relative_url }}).
```

2021-05-21 09:56 UTC, danielnordh commented on guide/private-key-management/introduction.md
> +### [Recovery phrase]({{ '/guide/private-key-management/recovery-phrase/' | relative_url }})
```suggestion
### [Manual backup of recovery phrase]({{ '/guide/private-key-management/manual-backup/' | relative_url }})
```

2021-05-21 09:57 UTC, danielnordh commented on guide/private-key-management/overview.md
> +- [Recovery phrase](/guide/private-key-management/recovery-phrase/) - manual backup of a phrase of words
```suggestion
- [Manual backup of recovery phrase](/guide/private-key-management/manual-backup/) - manual backup of a phrase of words
```

2021-05-21 10:01 UTC, danielnordh commented on guide/private-key-management/cloud-backup.md
> +Next, let's look at [Recovery phrase]({{ '/guide/private-key-management/recovery-phrase/' | relative_url }}).
```suggestion
Next, let's look at [manual backup of recovery phrase]({{ '/guide/private-key-management/recovery-phrase/' | relative_url }}).
```

2021-05-21 10:02 UTC, danielnordh commented on guide/private-key-management/introduction.md
> +### [Recovery phrase]({{ '/guide/private-key-management/recovery-phrase/' | relative_url }})
```suggestion
### [Manual backup of recovery phrase]({{ '/guide/private-key-management/recovery-phrase/' | relative_url }})
```

2021-05-21 10:02 UTC, danielnordh commented on guide/private-key-management/overview.md
> +- [Recovery phrase](/guide/private-key-management/recovery-phrase/) - manual backup of a phrase of words
```suggestion
- [Manual backup of recovery phrase](/guide/private-key-management/recovery-phrase/) - manual backup of a phrase of words
```

2021-05-21 10:03 UTC, danielnordh commented on guide/private-key-management/recovery-phrase.md
> +# Recovery phrase
```suggestion
# Manual backup of recovery phrase
```

2021-05-21 10:22 UTC, danielnordh commented
OK, here are my final thoughts on this, now only including minimal changes from what's currently in master:

- The title on the page changes to 'Manual backup of recovery phrase' (from 'Manual backup / Recovery phrase')
- The title in the sidebar changes to 'Recovery phrase' (from 'Manual backup')
- The permalink changes to 'recovery-phrase' (from 'manual-backup')

If people think these are no good changes I'll close this PR.
Not worth spending more time on this.

2021-05-21 10:55 UTC, GBKS commented
@ConorOkus could you chime in on the change from "Manual backup" to "Recovery phrase"? Might also be a consideration for as you have a page with the same name in Onboarding.

2021-05-22 05:37 UTC, Bosch-0 approved these changes

2021-05-24 07:53 UTC, ConorOkus commented
Ignoring the onboarding section for a second, I actually find this structure less clear than before. To me manual backup is using a method that involves physically managing the storage of a recovery phrase e.g writing it down on paper, etching it into steel. Auto vs Manual is basically physical vs non-physical which I find easier to grasp.

Here is the latest structure in the onboarding section - https://deploy-preview-302--sad-borg-390916.netlify.app/guide/onboarding/backing-up-a-recovery-phrase/

If we think that what is in onboarding is way off, then we can think about how we sync the two sections, but not sure if it is worth the effort.

2021-05-24 08:00 UTC, Bosch-0 commented
As there seems to be a difference of opinion on this how about we share this on slack to get more views. calling it Recovery phrase is still much clearer in my mind.

2021-05-27 17:31 UTC, pavlenex commented
Closing this one due to lack of consensus, let's focus on where we can to proceed with the V1. @danielnordh agreed we can close this one.

2021-05-27 17:31 UTC, closed without merging