Update usage-life-cycle.md
BitcoinDesign/Guide pull request #375
Opened 2021-06-04 09:50 UTC by pavlenex

Co-Authored-By: @sqctoucan

This is the part of #202 
The goal of this PR is to simplify the content without altering the context.

2021-06-07 14:24 UTC, johnsBeharry commented on guide/designing-products/usage-life-cycle.md
> +Barious [user research]({{ '/guide/designing-products/user-research/' | relative_url }}) techniques that can help identify and solve these types of issues
```suggestion
Various [user research]({{ '/guide/designing-products/user-research/' | relative_url }}) techniques that can help identify and solve these types of issues
```

2021-06-07 15:06 UTC, pavlenex commented on guide/designing-products/usage-life-cycle.md
> +Barious [user research]({{ '/guide/designing-products/user-research/' | relative_url }}) techniques that can help identify and solve these types of issues
rofl

2021-06-10 07:31 UTC, GBKS commented on guide/designing-products/usage-life-cycle.md
> +Various [user research]({{ '/guide/designing-products/user-research/' | relative_url }}) techniques that can help identify and solve these types of issues
```suggestion
There are various [user research]({{ '/guide/designing-products/user-research/' | relative_url }}) techniques that can help identify and solve these types of issues.
```
Sentence had no verb or period.

2021-06-10 07:34 UTC, GBKS commented on guide/designing-products/usage-life-cycle.md
> +The user decides to move forward with your product. They are still not familiar with exactly how it works, and their expectations may not match what your product offers. Therefore, it is crucial to t
```suggestion
The user decides to move forward with your product. They are still not familiar with exactly how it works, and their expectations may not match what your product offers. Therefore, it is crucial to pay close attention to the design of the [onboarding experience]({{ '/guide/onboarding/introduction/' | relative_url }}). Your product should make it easy for users to quickly and successfully solve problems while being introduced to your product's basics and best practices. This sets expectations for future interactions. If the first use is frustrating, users are less likely to use your product again—or to recommend it.
```
Not sure what is meant by `tightly managing the onboarding experience research`. It's the design of the experience that needs to be well-crafted.

2021-06-10 07:35 UTC, GBKS commented on guide/designing-products/usage-life-cycle.md
> +The following six sections outline a typical usage life cycle, from never having heard of your product to becoming one of its power users.
```suggestion
The following six phases outline a typical usage life cycle, from never having heard of your product to becoming one of its power users.
```
We use sections to refer to parts of the guide, so changing this to phases, which is also used in the following paragraph.

2021-06-10 07:37 UTC, GBKS requested changes
Looks good. Just had a few minor nits.

A good future update to this page would be to add more Bitcoin-specific recommendations to each phase.

2021-06-14 09:45 UTC, pavlenex commented
@GBKS I committed the suggestions you had, good ones. 🚀 This one is good to go once you take a final look at it.

2021-06-14 12:21 UTC, GBKS approved these changes
Just had another read through and it looks good. I'll open another issue for potentially adding more Bitcoin-specific info to each step.

2021-06-14 12:21 UTC, merged