Consolidate pros/cons sections in Coin Selection Page
BitcoinDesign/Guide pull request #436
Opened 2021-08-04 09:14 UTC by pavlenex

This is an attempt to cut down and make the pros/cons sections more concise.
It doesn't restructure things, simply cuts down on text trying to simplify it.
#360

2021-08-04 09:17 UTC, pavlenex commented
In https://github.com/BitcoinDesign/Guide/pull/436/commits/4ce6f2b93498bd9654175c25c16c559d04ed16c6 I removed a sentence that can potentially lead to a conclusion that the more UTXO's you select, the faster the transaction is, the only way to speed up is by paying a higher fee.

2021-08-04 09:26 UTC, johnsBeharry commented on guide/payments/coin-selection.md
>  - Freezing certain coins reduces the size of a wallet's UTXO pool, and may hinder an automatic algorithm’s ability to optimise for speed, cost, or privacy.
```suggestion
- Freezing coins reduces the available UTXOs an automatic coin selection algorithm can choose from so the resulting transaction may not be properly optimized.
```

2021-08-04 09:27 UTC, johnsBeharry commented on guide/payments/coin-selection.md
>  - Freezing certain coins reduces the size of a wallet's UTXO pool, and may hinder an automatic algorithm’s ability to optimise for speed, cost, or privacy.
can be less wordy...

2021-08-04 12:47 UTC, johnsBeharry commented on guide/payments/coin-selection.md
> +- Freezing coins reduces the available UTXOs an automatic coin selection algorithm can choose from so the resulting transaction may not be properly optimized.
```suggestion
- Freezing UTXOs prevents coin selection algorithms from using them, so the resulting transaction may not be properly optimized.
```

2021-08-06 08:39 UTC, Bosch-0 commented on guide/payments/coin-selection.md
> +Higher fees will increase the likelihood of your transaction being prioritized by miners and included in the next block, thereby increasing the speed of your transaction.
```suggestion
Higher fees will increase the likelihood of your transaction being prioritized by miners and included in the next block, thereby increasing the speed of your transaction being confirmed.
```

Small bit but It's important to add the context that when talking about speeding up a transaction it pertains to it being confirmed in the network.

2021-08-06 08:42 UTC, Bosch-0 requested changes
LGTM, left a few comments

2021-08-06 08:55 UTC, pavlenex commented
This one is good to go, needs final approval and merge, @Bosch-0 will address some points in another PR.

2021-08-06 09:13 UTC, Bosch-0 approved these changes

2021-08-06 09:29 UTC, johnsBeharry approved these changes
nice work on this!

2021-08-06 09:30 UTC, merged

2021-08-06 09:32 UTC, johnsBeharry commented
Oops sorry didn't realise you wanted Christoph to review before merge. was a bit too excited to see it updated.

2021-08-06 09:41 UTC, pavlenex commented
It's fine, either Christoph or you, first come first served 😂