Added signers to glossary
BitcoinDesign/Guide pull request #804
Opened 2022-05-06 03:09 UTC by Bosch-0

To get things rolling with https://github.com/BitcoinDesign/Guide/issues/792

2022-05-06 06:20 UTC, GBKS requested changes
We cannot use "Signer", it is too generic.

2022-05-06 06:20 UTC, GBKS commented on guide/glossary/index.md
> +### Signer
```suggestion
### Signing device
```

Signer is too generic, as discussed in #792. We have to use either signing device or hardware wallet.

2022-05-10 07:49 UTC, pavlenex approved these changes
LGMT

2022-05-25 11:26 UTC, GBKS commented
We have a paragraph about [hardware wallets](https://bitcoin.design/guide/getting-started/hardware/#hardware-wallets) in the "Hardware overview" page, and I'm not clear on how that relates to this glossary entry here. Why not add an "aka signing device" there instead?

2022-06-14 03:20 UTC, Bosch-0 commented
Lets re-address this when we get to expanding the savings wallet reference design

2022-06-14 03:20 UTC, closed without merging