Added Channel Reserve to Glossary
BitcoinDesign/Guide pull request #811
Opened 2022-05-11 08:24 UTC by Mogashni

Added a short paragraph explanation of channel reserve to glossary.

2022-05-12 14:06 UTC, sbddesign requested changes
Nice! 2 things:
- Need a comma
- Maybe we should specify "lightning payment channel" for someone who's unfamiliar?

For future PRs: one thing that's helpful for people reviewing is if you put the [deploy preview link](https://deploy-preview-811--sad-borg-390916.netlify.app/guide/glossary/#channel-reserve) in the description so they can skip directly to what they are reviewing.

2022-05-13 05:59 UTC, GBKS commented on guide/glossary/index.md
> +A channel reserve works as a type of insurance against theft. If a peer tries to cheat in a channel then the other party can submit a penalty transaction. This transaction will then take away all the
Good idea to work in the word lightning in this paragraph. Might otherwise not be clear which layer this is about.

2022-05-16 11:03 UTC, sbddesign approved these changes
💯

2022-05-16 13:18 UTC, Mogashni commented
Have added a link to the live preview at the top as well. Thanks for your comments!

2022-05-17 07:29 UTC, GBKS approved these changes
ACK. Good addition.

2022-05-18 03:39 UTC, merged