Adding the second edition of The State of Lightning by Arcane Research
BitcoinDesign/Guide pull request #845
Opened 2022-06-11 06:16 UTC by paulosacramento

2022-06-12 02:15 UTC, Bosch-0 commented on guide/resources/design-research.md
> +In this second edition, Arcane Research delivers valuable insights into the growth of Bitcoin's main payment layer. The report helps quantify and visualize what's happening right now with Lightning.
```suggestion
In this second edition, Arcane Research delivers valuable insights into the growth of bitcoin's lightning network. The report helps quantify and visualize what's happening right now with lightning. Not only that, it also shows how it is solving real problems for people around the world.
```

2022-06-12 02:15 UTC, Bosch-0 requested changes
LGTM, minor nit

2022-06-12 19:44 UTC, paulosacramento commented on guide/resources/design-research.md
> +In this second edition, Arcane Research delivers valuable insights into the growth of Bitcoin's main payment layer. The report helps quantify and visualize what's happening right now with Lightning.
Thanks for the correction.

2022-06-13 10:34 UTC, sbddesign commented
It looks like a login is required to view this research document?

2022-06-14 03:25 UTC, Bosch-0 commented
We discussed in the Jam session last night about avoiding linking users to resources they need to log in for to access such as this one. This goes against our views on having no tracking. We have two options about how we could do this: 

- Download and host these documents our selves
- Link to a third-party pdf (such as https://assets.ctfassets.net/4rilomtvvae4/4Q8jnXMVUDMovAY8hcpYkL/fb65b3290c8dcb23314aacb6f9b19be6/The_State_of_Lightning_Vol_2.pdf for this article) 

Thoughts?

2022-06-16 14:49 UTC, GBKS commented
I don't think we should host files whose authors restrict their access. Either we add a note ("requires login") on the page, or we just don't list it.

2022-06-17 05:33 UTC, paulosacramento commented
I'm in favor of adding the _requires login_ note.

2022-06-23 10:54 UTC, pavlenex commented
> I don't think we should host files whose authors restrict their access. Either we add a note ("requires login") on the page, or we just don't list it.

Agreed, just add a note, a label. I think people would def miss out on things, some of those insights are really helpful and TBH people can just use a fake email, so it's not really a big deal imo.

2022-06-24 13:19 UTC, GBKS commented on guide/resources/design-research.md
> +_2022 by Arcane research_
```suggestion
_Login required to access. 2022 by Arcane research_
```

2022-06-24 13:19 UTC, GBKS commented
Made a suggestion for a login note. There's also a conflict that needs to be resolved, is that something you're comfortable doing, @paulosacramento?

2022-06-25 06:43 UTC, paulosacramento commented
> Made a suggestion for a login note. There's also a conflict that needs to be resolved, is that something you're comfortable doing, @paulosacramento?

I tried but could not resolve the conflict. It would be great if you or someone else could solve this.

2022-06-27 17:29 UTC, GBKS commented on guide/resources/design-research.md
> +_2022 by Arcane research_
@paulosacramento you'll have to press `Commit suggestion` above if you want to accept the change. `Resolve conversation` only closes the conversation without accepting the change.

2022-06-27 17:30 UTC, GBKS commented
@paulosacramento I fixed the conflict.

Did you mean to accept or dismiss the change I suggested for the "Login required" copy?

2022-06-27 19:08 UTC, paulosacramento reviewed
I hope i did it right. LOL

2022-06-28 02:56 UTC, Bosch-0 approved these changes

2022-06-28 02:57 UTC, merged