Adds research on transaction list by Alby
BitcoinDesign/Guide pull request #929
Opened 2022-09-23 08:31 UTC by GBKS

Added a brief summary to the activity page, and a link on the research page.

Closes #926

2022-09-23 10:28 UTC, pavlenex commented on guide/daily-spending-wallet/activity.md
> +[Research](https://blog.getalby.com/rethinking-transaction-lists/) by the team at [Alby](https://getalby.com) has indicated that most users rarely visit transaction list. The most common reasons to d
```suggestion
[Research](https://blog.getalby.com/rethinking-transaction-lists/) by the team at [Alby](https://getalby.com) has indicated that most users rarely visit a transaction list. The most common reasons to do so are to confirm payment status, budgeting and to analyze payment behavior. The biggest challenges are navigating through endless lists to find a specific transaction and unavailable metadata leaving users guessing who the payment was sent to and what for.	
```

2022-09-23 11:15 UTC, MoritzKa commented
Great that we can contribute. Looks good for me.

2022-10-10 13:31 UTC, sbddesign requested changes
Grammar nits, but looks like a great addition otherwise.

2022-10-10 13:31 UTC, sbddesign commented on guide/daily-spending-wallet/activity.md
> +[Research](https://blog.getalby.com/rethinking-transaction-lists/) by the team at [Alby](https://getalby.com) has indicated that most users rarely visit a transaction list. The most common reasons to
```suggestion
[Research](https://blog.getalby.com/rethinking-transaction-lists/) by the team at [Alby](https://getalby.com) has indicated that most users rarely visit a transaction list. The most common reasons to do so are to confirm payment status, budgeting, and to analyze payment behavior. The biggest challenges are navigating through endless lists to find a specific transaction and unavailable metadata, leaving users guessing who the payment was sent to and what for.	
```

2022-10-10 13:37 UTC, sbddesign approved these changes
👻

2022-10-10 13:39 UTC, merged