Change "lightning network" to lowercase
BitcoinDesign/Guide pull request #930
Opened 2022-09-25 15:59 UTC by jakubszwedo

This PR changes "lightning network" to lowercase across the whole guide, except when it's the beginning of the sentence, a title for a section or subsection or when it's a part of a research/paper title.

Related discussion: #890

2022-09-26 03:16 UTC, Bosch-0 submitted a review, later dismissed
LGTM, thanks a bunch for this Jakub!

2022-09-29 08:25 UTC, pavlenex commented on guide/daily-spending-wallet/sending.md
> +      caption: lightning transactions typically complete in seconds and don't require loaders.
Well this one is beginning of the sentence?

2022-10-03 13:11 UTC, GBKS commented on guide/daily-spending-wallet/sending.md
> +imageslightning:
This is a variable name and should not be changed.

2022-10-03 13:12 UTC, GBKS commented on guide/daily-spending-wallet/sending.md
> +{% include image-gallery.html pages = page.imageslightning %}
Variable name again. Should stay as is.

2022-10-03 15:28 UTC, GBKS requested changes
Found several spots where capitalization was incorrectly changed. Please review.

2022-10-03 15:28 UTC, GBKS commented on guide/resources/design-research.md
> +#### [A Deep Dive Into Lightning as a Bitcoin Scaling Solution](https://downloads.coindesk.com/research/lightning+Network+-+CoinDesk+Research+-+2021.09.pdf)
Used in a link, should not be changed.

2022-10-03 15:28 UTC, GBKS commented on guide/how-it-works/lightning-services.md
> +   previousName = "lightning liquidity"
Start of a tooltip sentence, should not be changed.

2022-10-03 15:28 UTC, GBKS commented on guide/how-it-works/lightning-services.md
> +   image = "/assets/images/guide/how-it-works/lightning-services/lightning-address.png"
Used in file names, should not be changed.

2022-10-03 15:28 UTC, GBKS commented on guide/how-it-works/lightning-services.md
> +This section covers two categories of lightning services: lightning service providers (LSPs), which focus on onboarding and providing connectivity to lightning users, and [lightning wallet servers]({
Used after a colon, should not be changed.

2022-10-11 07:25 UTC, GBKS approved these changes
ACK. Thanks for the extra revision.

2022-10-11 07:27 UTC, merged